Repository etjump/etjump, pull requests merged in 2020-07, with the labels that each got.

#501 reduce cgaz2 tris count, skip drawing cgaz2 angles when under velocity threshold for strafing
  src/cgame/cg_draw.cpp
Labels: enhancement, feature

#503 Minor chat fix/refactor
  src/cgame/cg_draw.cpp
Labels: enhancement

#505 Fix CHS2 menu overlap
  etjump/ui/etjump_settings_4.menu
Labels: bug
