Repository etjump/etjump, pull requests merged in 2021-02, with the labels that each got.

#576 Fix timerun prints on runs over 1 hour
  src/cgame/cg_timerun.cpp
  src/cgame/cg_timerun.h
Labels: bug

#579 add constantLight support back to movers
  src/game/g_mover.cpp
Labels: feature

#580 add customizable noise to func_button
  src/game/g_mover.cpp
Labels: enhancement, feature

#582 add spawnflag to override func_static activation delay
  src/game/g_mover.cpp
Labels: enhancement, feature

#585 Fix weapons potentially set at WP_NONE when using team command
  src/game/g_cmds.cpp
  src/game/g_local.h
Labels: bug

#587 Allow banner hiding in demo playback
  src/cgame/cg_draw.cpp
  src/cgame/cg_local.h
  src/cgame/cg_main.cpp
Labels: feature
