Repository etjump/etjump, pull requests merged in 2021-09, with the labels that each got.

#683 Fix strafe quality issues
  src/cgame/etj_snaphud.cpp
  src/cgame/etj_snaphud.h
  src/cgame/etj_strafe_quality_drawable.cpp
  src/cgame/etj_strafe_quality_drawable.h
  src/game/q_shared.h
Labels: bug, enhancement

#685 Fix crash with ETe
  src/cgame/etj_pmove_utils.cpp
  src/cgame/etj_strafe_quality_drawable.cpp
Labels: bug

#686 Disable CGaz/snaphud in noclip, fix MAX_SNAPHUD_ZONES_Q1 correctness
  src/cgame/etj_cgaz.cpp
  src/cgame/etj_snaphud.cpp
  src/cgame/etj_snaphud.h
  src/game/bg_pmove.cpp
Labels: bug, enhancement

#687 Clamp velocityScale, more max snapzones correctness
  src/cgame/etj_snaphud.cpp
  src/cgame/etj_snaphud.h
  src/game/g_active.cpp
Labels: enhancement

#691 Fix snaphud crash when joining team with user input
  src/cgame/etj_snaphud.cpp
Labels: bug

#694 Link some missing weapon sound events to `etj_weaponVolume`
  src/cgame/cg_event.cpp
  src/cgame/cg_local.h
  src/cgame/cg_newDraw.cpp
  src/cgame/cg_syscalls.cpp
  src/cgame/cg_weapons.cpp
Labels: bug, enhancement

#697 Fix msg indices in Cmd_Vote_f function
  src/game/g_cmds.cpp
Labels: bug

#698 Fix windows binaries not included in packing + add pdb files
  ci/azure-pipelines-release.yml
Labels: build system

#700 Fix windows packing + add pdb files
  ci/azure-pipelines-release.yml
Labels: build system

#702 Fix unnecessary drawing/updating of cgaz/snaphud/strafe quality
  src/cgame/etj_cgaz.cpp
  src/cgame/etj_snaphud.cpp
  src/cgame/etj_strafe_quality_drawable.cpp
Labels: enhancement

#723 Fix prediction error with save
  src/cgame/cg_consolecmds.cpp
  src/cgame/cg_draw.cpp
  src/cgame/cg_event.cpp
  src/cgame/cg_local.h
  src/cgame/cg_main.cpp
  src/cgame/cg_servercmds.cpp
  src/cgame/etj_jump_speeds.cpp
  src/cgame/etj_jump_speeds.h
  src/game/etj_save_system.cpp
  src/game/etj_save_system.h
Labels: bug, enhancement

#725 Fix MAX_CS calculation
  src/game/bg_public.h
Labels: bug

#729 Remove `g_saveMsg`, add `etj_saveMsg`
  assets/ui/etjump_settings_1.menu
  src/cgame/cg_local.h
  src/cgame/cg_main.cpp
  src/cgame/cg_servercmds.cpp
  src/game/etj_save_system.cpp
  src/game/etj_save_system.h
  src/game/g_local.h
  src/game/g_main.cpp
  src/game/g_target.cpp
Labels: enhancement, feature

#733 Fix jumpspeeds drawing when scoreboard is up
  src/cgame/etj_jump_speeds.cpp
Labels: bug
