Repository etjump/etjump, pull requests merged in 2023-07, with the labels that each got.

#957 Fix portalgun trace not skipping ET_TEMPHEAD
  src/game/g_weapon.cpp
Labels: Bug

#959 Fix portal trails not respecting etj_viewPlayerPortals
  src/cgame/cg_ents.cpp
  src/cgame/cg_event.cpp
  src/game/bg_public.h
  src/game/g_weapon.cpp
Labels: Bug, Enhancement

#962 Allow fast respawn + load after gib
  src/game/etj_save_system.cpp
Labels: Enhancement

#965 Run update on CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: Build System

#964 Improve spectator info list
  assets/ui/etjump_settings_5.menu
  src/cgame/CMakeLists.txt
  src/cgame/cg_draw.cpp
  src/cgame/cg_local.h
  src/cgame/cg_main.cpp
  src/cgame/etj_init.cpp
  src/cgame/etj_spectatorinfo_drawable.cpp
  src/cgame/etj_spectatorinfo_drawable.h
Labels: Enhancement

#966 Center CGaz 2 + small cleanup
  src/cgame/etj_cgaz.cpp
Labels: Enhancement

#968 Fix incorrect destsize for TeamplayInfoMessage
  src/game/g_team.cpp
Labels: Bug

#974 Fix menu key out of bounds access
  src/ui/ui_main.cpp
Labels: Bug

#975 Fix constructible classes out of bounds access
  src/game/g_mover.cpp
Labels: Bug

#976 Fix bad format specifier in VoiceTo function
  src/game/g_cmds.cpp
Labels: Bug

#977 Fix memset size for item visuals
  src/cgame/cg_weapons.cpp
Labels: Bug

#978 Fix unused argument in speaker error format str
  src/game/bg_sscript.cpp
Labels: Bug

#979 Fix null dereference in killtrails
  src/cgame/cg_trails.cpp
Labels: Bug

#980 Fix null dereference in damage inflictor
  src/game/g_props.cpp
Labels: Bug

#983 Proper fix for health regen with pmove_fixed 1
  src/game/g_active.cpp
Labels: Bug, Enhancement

#984 Fix players not drowning with pmove_fixed 1 and high fps
  src/game/g_active.cpp
Labels: Bug

#967 Add warning about running server with fixed patch collision
  src/game/g_main.cpp
Labels: Feature

#986 Add nodrop worldspawn key
  src/cgame/cg_localents.cpp
  src/game/bg_misc.cpp
  src/game/bg_public.h
  src/game/g_client.cpp
  src/game/g_combat.cpp
  src/game/g_items.cpp
  src/game/g_local.h
  src/game/g_spawn.cpp
Labels: Feature

#987 Default cg_runroll and cg_runpitch to 0
  src/cgame/cg_main.cpp
Labels: Enhancement
