Repository etjump/etjump, pull requests merged in 2024-08, with the labels that each got.

#1406 Add dropdown menus
  assets/ui/etjump_settings_general_console.menu
  assets/ui/etjump_settings_general_gameplay.menu
  assets/ui/etjump_settings_graphics_players.menu
  assets/ui/etjump_settings_hud1_crosshair.menu
  assets/ui/etjump_settings_hud1_indicators.menu
  assets/ui/etjump_settings_hud1_keys.menu
  assets/ui/etjump_settings_hud1_speed2.menu
  assets/ui/etjump_settings_hud2_accelspeed.menu
  assets/ui/etjump_settings_hud2_cgaz.menu
  assets/ui/etjump_settings_hud2_chs.menu
  assets/ui/etjump_settings_hud2_chs1.menu
  assets/ui/etjump_settings_hud2_chs2.menu
  assets/ui/etjump_settings_hud2_jumpspeeds.menu
  assets/ui/etjump_settings_hud2_snaphud.menu
  assets/ui/etjump_settings_hud2_strafequality.menu
  assets/ui/etjump_settings_hud2_upmove.menu
  assets/ui/etjump_settings_timeruns_runtimer.menu
  assets/ui/menudef_ext.h
  assets/ui/menumacros_ext.h
  src/ui/ui_shared.cpp
  src/ui/ui_shared.h
Labels: Enhancement, Feature

#1407 Flamethrower fps dependency fixes
  src/game/bg_public.h
  src/game/g_local.h
  src/game/g_missile.cpp
  src/game/g_weapon.cpp
Labels: Bug, Cleanup

#1408 Fix diagonal pack throws
  src/game/bg_misc.cpp
  src/game/bg_public.h
  src/game/q_math.cpp
  src/game/q_shared.h
Labels: Bug

#1409 Cleanup & fix ETL client detection
  assets/ui/main.menu
  src/game/q_shared.h
  src/ui/ui_local.h
  src/ui/ui_main.cpp
Labels: Bug, Cleanup

#1382 Add autospec
  src/cgame/cg_local.h
  src/cgame/cg_main.cpp
  src/cgame/etj_init.cpp
Labels: Feature

#1410 Combine etj_playerBBoxBottomOnly* cvars into single cvar
  assets/ui/etjump_settings_graphics_players.menu
  src/cgame/cg_local.h
  src/cgame/cg_main.cpp
  src/cgame/etj_player_bbox.cpp
Labels: Enhancement

#1411 Add menu entries for autospec
  assets/ui/etjump_settings_general_gameplay.menu
Labels: Enhancement

#1412 Fix flamechunk lifetime
  src/game/g_missile.cpp
Labels: Bug

#1419 Reset listbans colors after bannedBy entry
  src/game/etj_database.cpp
Labels: Bug

#1415 Add adminchat
  assets/ui/ingame_messagemode.menu
  src/cgame/cg_consolecmds.cpp
  src/game/bg_public.h
  src/game/etj_commands.cpp
  src/game/etj_commands.h
  src/game/g_cmds.cpp
  src/game/g_local.h
  src/game/g_main.cpp
Labels: Feature

#1417 Add IP to !userinfo
  src/game/etj_database.cpp
  src/game/etj_session.cpp
  src/game/etj_session.h
Labels: Enhancement

#1420 Fix potential OOB read in menu->onKey
  src/ui/keycodes.h
  src/ui/ui_shared.cpp
  src/ui/ui_shared.h
Labels: Bug

#1421 Parse custom string values in menu properly
  src/game/etj_string_utilities.cpp
  src/game/etj_string_utilities.h
  src/ui/ui_shared.cpp
Labels: Bug, Enhancement

#1424 Fix listbox drag losing focus when mouse exits rect
  src/ui/ui_shared.cpp
Labels: Enhancement

#1425 Set focus to writeconfig prompt on menu open
  assets/ui/etjump_settings_popup_writeconfig.menu
Labels: Bug

#1426 Add PC_Boolean_Parse
  assets/ui/menumacros_ext.h
  src/game/bg_public.h
  src/ui/ui_shared.cpp
  src/ui/ui_shared.h
Labels: Enhancement

#1427 Fix tooltips not drawing for focused edit/numericfields
  src/ui/ui_shared.cpp
Labels: Bug
