Repository etjump/etjump, pull requests merged in 2024-02, with the labels that each got.

#1186 Fix noclipping spectators drawing as axis soldiers
  src/game/bg_misc.cpp
Labels: Bug

#1191 Increase UI mempool size
  src/ui/ui_shared.cpp
Labels: Bug

#1192 don't allow setoffset through nonoclip zones
  src/game/g_cmds.cpp
Labels: Bug

#1185 Improve entity health bar visuals
  src/cgame/cg_draw.cpp
  src/cgame/cg_drawtools.cpp
  src/cgame/cg_local.h
  src/cgame/cg_newDraw.cpp
Labels: Enhancement

#1194 Update workflow checkout/upload to v4
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverity.yml
  .github/workflows/release.yml
Labels: Build System

#1195 add grenade support for target_give
  src/game/bg_public.h
  src/game/g_items.cpp
Labels: Feature

#1196 Fix crash when cooked grenade was removed by init or starttimer
  src/game/etj_target_init.cpp
  src/game/etj_utilities.cpp
Labels: Bug

#1199 Cleanup eflags
  src/cgame/cg_ents.cpp
  src/cgame/cg_predict.cpp
  src/game/bg_public.h
Labels: Cleanup

#1200 Fix chat mentions breaking chat coloring
  src/game/g_cmds.cpp
  src/game/g_local.h
  src/game/g_utilities.cpp
Labels: Bug

#1201 Make static coronas client side only
  src/cgame/cg_draw.cpp
  src/cgame/cg_ents.cpp
  src/cgame/cg_local.h
  src/cgame/cg_spawn.cpp
  src/game/g_misc.cpp
Labels: Enhancement, Feature

#1202 Fix comment on entitystate number bits
  src/game/q_shared.h
Labels: Bug

#1203 Fix speaker editor + improve visuals
  src/cgame/cg_sound.cpp
  src/ui/ui_shared.cpp
Labels: Bug

#1204 fix tracker_not_eq overriding other checks
  src/game/etj_progression_tracker.cpp
Labels: Bug

#1208 Support arm64 on macOS
  .github/workflows/ci.yml
  .github/workflows/release.yml
  cmake/PlatformDetails.cmake
  src/game/g_main.cpp
Labels: Build System

#1209 add "usetarget" to mapscripts, add activator-support to func_invisible user
  src/game/g_mover.cpp
  src/game/g_script.cpp
  src/game/g_script_actions.cpp
Labels: Enhancement, Feature

#1210 Add basic demo compatibility checker + fix client-only coronas on old demos
  src/cgame/CMakeLists.txt
  src/cgame/cg_draw.cpp
  src/cgame/cg_local.h
  src/cgame/etj_demo_compatibility.cpp
  src/cgame/etj_demo_compatibility.h
  src/cgame/etj_init.cpp
Labels: Feature

#1214 Improve callvote strings
  src/game/g_cmds.cpp
  src/game/g_local.h
  src/game/g_vote.cpp
Labels: Enhancement

#1206 Fix use-after-scope in SaveNameOperation
  src/game/etj_database.cpp
Labels: Bug

#1215 Rock the vote [maplist]
  src/cgame/etj_client_rtv_handler.cpp
  src/game/etj_custom_map_votes.cpp
  src/game/etj_custom_map_votes.h
  src/game/etj_main_ext.cpp
  src/game/g_cmds.cpp
  src/game/g_local.h
  src/game/g_vote.cpp
Labels: Enhancement

#1216 Fix linker errors in progression tracker
  src/game/etj_progression_tracker.h
Labels: Bug

#1218 Fix div by 0 in flame chunk code
  src/cgame/cg_flamethrower.cpp
Labels: Bug

#1221 Disallow loading with mortar set to a prone position
  src/game/etj_save_system.cpp
Labels: Bug

#1219 Fix rename issues
  src/game/etj_commands.cpp
  src/game/g_client.cpp
  src/game/g_local.h
Labels: Bug, Enhancement

#1223 Fix goto/call/iwant stance exploit
  src/game/etj_utilities.cpp
  src/game/etj_utilities.h
  src/game/g_cmds.cpp
Labels: Bug

#1224 Fix rtv with no args + !rtv [list] command
  src/cgame/cg_servercmds.cpp
  src/game/etj_commands.cpp
  src/game/g_vote.cpp
Labels: Bug, Enhancement

#1225 Fix limbopanel button mouseovers on widescreen
  src/cgame/cg_limbopanel.cpp
  src/ui/ui_shared.cpp
  src/ui/ui_shared.h
Labels: Bug

#1227 Fix Weapon_AdrenalineSyringe adding wrong value to PW_ADRENALINE
  src/game/g_weapon.cpp
Labels: Bug

#1229 Fix client-side FPS dependencies
  src/cgame/cg_particles.cpp
  src/cgame/cg_predict.cpp
  src/cgame/cg_view.cpp
  src/game/bg_pmove.cpp
  src/game/bg_public.h
  src/game/g_cmds.cpp
  src/game/g_misc.cpp
  src/game/q_shared.h
Labels: Bug

#1231 Fix spec noclip not getting deactivated when entering no-nonclip area
  src/game/g_active.cpp
Labels: Bug

#1235 Improve entitylist output
  src/game/g_svcmds.cpp
Labels: Enhancement
