Repository etjump/etjump, pull requests merged in 2024-01, with the labels that each got.

#1144 Multiactivator triggers by default + deprecate spawnflags 512 & 2048
  src/game/g_active.cpp
  src/game/g_local.h
  src/game/g_main.cpp
  src/game/g_trigger.cpp
Labels: Enhancement, Cleanup

#1145 Fix backups breaking on initial save to a slot + cleanup save code
  src/game/etj_save_system.cpp
  src/game/etj_save_system.h
Labels: Bug, Cleanup

#1146 Misc RTV fixes
  src/game/etj_rtv.cpp
  src/game/etj_rtv.h
  src/game/g_cmds.cpp
  src/game/g_vote.cpp
Labels: Bug, Enhancement

#1148 Fix records query when mapname has partial match to another map + support partial matching
  src/game/etj_timerun_repository.cpp
Labels: Bug, Enhancement

#1150 Round jump speeds instead of truncating
  src/game/bg_pmove.cpp
Labels: Enhancement

#1151 Update JsonCpp to 1.9.5
  deps/json/CMakeLists.txt
  deps/json/json-forwards.h
  deps/json/json.h
  deps/json/json/json-forwards.h
  deps/json/json/json.h
  deps/json/jsoncpp.cpp
  src/cgame/etj_trickjump_lines.cpp
  src/game/etj_custom_map_votes.cpp
  src/game/etj_map_statistics.cpp
  src/game/etj_motd.cpp
  src/game/etj_tokens.cpp
  src/game/etj_tokens.h
Labels: Build System

#1153 Fix rtv vote counts breaking on "no" to "re-vote yes" scenarios
  src/game/g_cmds.cpp
Labels: Bug

#1149 Store timerun state with save slots
  src/game/etj_save_system.cpp
  src/game/etj_save_system.h
  src/game/etj_utilities.cpp
Labels: Enhancement

#1155 Add nowallbug worldspawn key
  src/game/bg_pmove.cpp
  src/game/bg_public.h
  src/game/g_local.h
  src/game/g_spawn.cpp
Labels: Feature

#1156 Don't start timeruns if client toggled pmove_fixed before
  src/game/etj_timerun_entities.cpp
  src/game/g_active.cpp
  src/game/g_local.h
Labels: Enhancement, Feature

#1152 Add custom vote editing via admin commands
  src/cgame/cg_consolecmds.cpp
  src/game/CMakeLists.txt
  src/game/etj_commands.cpp
  src/game/etj_custom_map_votes.cpp
  src/game/etj_custom_map_votes.h
  src/game/etj_json_utilities.cpp
  src/game/etj_json_utilities.h
  src/game/etj_main_ext.cpp
Labels: Enhancement, Feature

#1157 Add noclip shader + noclip indicator
  assets/gfx/2d/noclipicon.tga
  assets/scripts/trickjump.shader
  assets/ui/etjump_settings_3.menu
  src/cgame/CMakeLists.txt
  src/cgame/cg_draw.cpp
  src/cgame/cg_local.h
  src/cgame/cg_main.cpp
  src/cgame/etj_areaindicator_drawable.cpp
  src/cgame/etj_areaindicator_drawable.h
  src/cgame/etj_init.cpp
  src/game/bg_public.h
  src/game/etj_utilities.cpp
  src/game/etj_utilities.h
  src/game/g_active.cpp
  src/game/g_cmds.cpp
  src/game/g_local.h
  src/game/g_spawn.cpp
  src/game/surfaceflags.h
Labels: Enhancement, Feature

#1136 play short fall footstep on cushions
  assets/ui/etjump_settings_1.menu
  src/cgame/cg_event.cpp
  src/cgame/cg_local.h
  src/cgame/cg_main.cpp
  src/game/bg_misc.cpp
  src/game/bg_pmove.cpp
  src/game/bg_public.h
Labels: Bug, Feature

#1159 Fix crash when activating trigger_multiple via mapscript
  src/game/g_trigger.cpp
Labels: Bug

#1160 Fix unnecessary copy when assigning new backups after reset
  src/game/etj_save_system.cpp
Labels: Enhancement

#1161 clean up surfaceflags.h
  src/game/bg_pmove.cpp
  src/game/bg_public.h
  src/game/g_weapon.cpp
  src/game/surfaceflags.h
Labels: Cleanup

#1162 Fix ob detector drawing in wrong position
  src/cgame/etj_overbounce_detector.cpp
Labels: Bug

#1163 Fix being unable activate multiple trigger_multiples at the same time
  src/game/g_local.h
  src/game/g_trigger.cpp
Labels: Bug

#1164 Improve autortv prints and behavior
  src/game/etj_rtv.cpp
  src/game/etj_rtv.h
  src/game/g_vote.cpp
Labels: Enhancement

#1165 Fix typos in function names
  src/cgame/etj_awaited_command_handler.cpp
  src/cgame/etj_client_authentication.cpp
  src/cgame/etj_client_commands_handler.cpp
  src/cgame/etj_client_commands_handler.h
  src/cgame/etj_init.cpp
  src/cgame/etj_jump_speeds.cpp
  src/cgame/etj_overbounce_watcher.cpp
  src/game/etj_banner_system.cpp
  src/game/etj_common.h
  src/game/etj_main.cpp
  tests/client_commands_handler_tests.cpp
  tests/entity_events_handler_tests.cpp
Labels: Cleanup

#1166 Fix double footsteps on cushion + etj_fixedCushionSteps prediction
  src/cgame/cg_event.cpp
  src/game/bg_pmove.cpp
Labels: Bug

#1167 Fix rtv state being uninitialized on initial client connect
  src/cgame/etj_client_rtv_handler.cpp
  src/cgame/etj_client_rtv_handler.h
  src/cgame/etj_init.cpp
Labels: Bug

#1168 Always interrupt timeruns when client goes to spec
  src/game/g_cmds.cpp
Labels: Enhancement

#1169 Add comments indicating killpath for trap_Error calls
  src/cgame/cg_syscalls.cpp
  src/game/g_syscalls.cpp
  src/ui/ui_syscalls.cpp
Labels: Build System

#1173 Prevent potential div by 0 in playanim and accum code
  src/game/g_script_actions.cpp
Labels: Bug

#1177 Update g_oss value to reflect correct macOS support
  src/game/g_main.cpp
Labels: Bug

#1178 Don't start timeruns if setoffset was used after respawn
  src/game/etj_timerun_entities.cpp
  src/game/g_cmds.cpp
  src/game/g_local.h
Labels: Enhancement

#1180 Fix heap buffer overflow in client rtv menu
  src/cgame/etj_rtv_drawable.cpp
Labels: Bug
